// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlkcDd5UUXDg6IUlTfJtHu2WdW9JolqiI',
    appId: '1:564390033293:web:d0306296141c52a284efc4',
    messagingSenderId: '564390033293',
    projectId: 'skillfox-dev',
    authDomain: 'skillfox-dev.firebaseapp.com',
    storageBucket: 'skillfox-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5Smb3qCgtYgeIxud6_WRwPF9T_y8vgW4',
    appId: '1:564390033293:android:051e4e62b71c6b5984efc4',
    messagingSenderId: '564390033293',
    projectId: 'skillfox-dev',
    storageBucket: 'skillfox-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQRGLnDlpWYRmcNDin7g6K5FCIXKYmhIs',
    appId: '1:564390033293:ios:30e79ecfd89d0c1284efc4',
    messagingSenderId: '564390033293',
    projectId: 'skillfox-dev',
    storageBucket: 'skillfox-dev.firebasestorage.app',
    iosBundleId: 'com.example.skillfox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQRGLnDlpWYRmcNDin7g6K5FCIXKYmhIs',
    appId: '1:564390033293:ios:30e79ecfd89d0c1284efc4',
    messagingSenderId: '564390033293',
    projectId: 'skillfox-dev',
    storageBucket: 'skillfox-dev.firebasestorage.app',
    iosBundleId: 'com.example.skillfox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlkcDd5UUXDg6IUlTfJtHu2WdW9JolqiI',
    appId: '1:564390033293:web:311461dd6a0e977284efc4',
    messagingSenderId: '564390033293',
    projectId: 'skillfox-dev',
    authDomain: 'skillfox-dev.firebaseapp.com',
    storageBucket: 'skillfox-dev.firebasestorage.app',
  );
}
